### ISSUE TITLE
Welcome Screen Redesign (Mobile App)

### ISSUE THREAD

**Issue by sladanyi** [mozioinc/Mozio-Design#18]
Redo the top portion of the welcome.

![mozio-welcome](https://cloud.githubusercontent.com/assets/16884101/16497860/05f55bc0-3ec7-11e6-8a07-12250529b56e.png)

**Comment by sladanyi** [comment]
here is the style I've been using so far.

![mobile-style](https://cloud.githubusercontent.com/assets/16884101/16591383/aaa58c72-42a9-11e6-9cfa-a2ff1b40fce1.png)

**Comment by sladanyi** [comment]
![mobile-style-2](https://cloud.githubusercontent.com/assets/16884101/16591399/c006c6b2-42a9-11e6-893d-978f11d5ca3b.png)

**Comment by fsarria** [comment]
@sladanyi do you have the vector files of the last screen?
