### ISSUE TITLE
Design "About Screen" for Mobile App

### ISSUE THREAD

**Issue by sladanyi** [mozioinc/Mozio-Design#25]
Fede, can you finish designing the About Screen for the mobile? I didn't get a chance to finish it. Due date is end of day on Thursday, so developers can implement it on Friday.

Here is the wireframe for about screen: https://drive.google.com/open?id=0B18-VQLGYzAYZ1V6YzhWbHFwc2c

The PSD file can be found here:
https://drive.google.com/open?id=0B18-VQLGYzAYVUZ4WjhGS3F5V2s

**Comment by fsarria** [comment]
Hi @sladanyi, @hellolucas I don't have access to the files.

Can you give me permission? 

Thanks!

**Comment by hellolucas** [comment]
solved

**Comment by fsarria** [comment]
The Screens:

https://drive.google.com/open?id=0B2zfN7gBKu86WTZtMExoWTVHZWc
